version: "3.4"
services:
  frontend:
    image: madnificent/ember:3.15.2
    volumes:
      - ./frontend-rdfa-editor-demo:/app
    command: "ember serve --proxy http://demo-backend.say-editor.com"
  sftp:
    image: atmoz/sftp
    volumes:
      - ./frontend-rdfa-editor-demo:/home/rdfa/frontend-rdfa-editor-demo
    ports:
      - "2222:22"
